import React from 'react';
import './global.css';
import Providers from './providers';

export const metadata = {
  title: 'Welcome to public',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: React.ReactNode
}
 
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  )
}
